EMAIL: '<email to send to>'
SENDGRID_APIKEY: '<send grid api key>'
OPENTABLE_ID: '<open table restaurant id>'
DATETIME: '<date to query reservation search around>'
PEOPLE: '<number of people for reservation>'
DATE_SEARCH_START: '<filter search start date>'
DATE_SEARCH_END: '<filter search end date>'
TIME_SEARCH_START: '<filter earliest time available>'
TIME_SEARCH_END: '<filter latest time available>'
